// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ducepwutpqxmzfoqrgmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1Y2Vwd3V0cHF4bXpmb3FyZ215Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2ODI0MjksImV4cCI6MjA3NDI1ODQyOX0.fUWBurRDCplrI71G8kaZGi3xaA1wGCjsGAZAWgG71Gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});